all:
	g++ Source/Main.cpp Headers/Transformations.hpp Source/Transformations.cpp Headers/Events.hpp Source/Events.cpp Headers/FragmentShaderInit.hpp Source/FragmentShaderInit.cpp Headers/VertexShaderInit.hpp Source/VertexShaderInit.cpp Headers/Circle.hpp Source/Circle.cpp -lglfw -lGL -lGLEW -lm -o main_run
	
run:
	./main_run
	

clean:
	rm main_run
