all:
	g++ Source/Main.cpp Headers/Events.hpp Source/Events.cpp Headers/FragmentShaderInit.hpp Source/FragmentShaderInit.cpp Headers/VertexShaderInit.hpp Source/VertexShaderInit.cpp -lglfw -lGL -lGLEW -lm -o main_run
	
run:
	./main_run
	rm main_run
